# Generated by Django 3.2.18 on 2023-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='قريبا', max_length=255)),
                ('title', models.CharField(default='قريبا', max_length=255)),
            ],
        ),
    ]
